package org.jundragon.blogsearcher.core.mock;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Collectors;
import org.jundragon.blogsearcher.core.blog.application.port.output.BlogStatisticRepository;
import org.jundragon.blogsearcher.core.blog.domain.BlogKeyword;

public class FakeBlogStatisticRepository implements BlogStatisticRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<BlogKeyword> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public void save(BlogKeyword blogKeyword) {
        if (blogKeyword.getId() == null || blogKeyword.getId() == 0) {
            BlogKeyword newKeyword = BlogKeyword.builder()
                .id(autoGeneratedId.incrementAndGet())
                .keyword(blogKeyword.getKeyword())
                .count(1L)
                .build();
            data.add(newKeyword);
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), blogKeyword.getId()));
            data.add(blogKeyword);
        }
    }

    @Override
    public Optional<BlogKeyword> findByKeyword(String keyword) {
        return data.stream().filter(
            item -> item.getKeyword().equals(keyword)
        ).findAny();
    }

    @Override
    public List<BlogKeyword> getKeywordOrderByCountDescTop(Long top) {
        return data.stream()
            .sorted(Comparator.comparing(BlogKeyword::getCount).reversed())
            .limit(top)
            .collect(Collectors.toList());
    }
}
